name: Build songbook
on: [push]
jobs:
  build-songbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run make generate in Docker
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace chordpro/chordpro:latest make generate

      - name: Create GitHub Release
        id: release
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')" # Use a timestamp for the release version
          RELEASE_NOTE="Release generated PDF for commit ${GITHUB_SHA}"
          gh release create "$TAG_NAME" book.pdf --title "$TAG_NAME" --notes "$RELEASE_NOTE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload book.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: book.pdf