name: Build songbook
on: [push]
jobs:
  build-songbook:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Run 'make generate' inside the chordpro docker container
      - name: Run make generate in Docker
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace chordpro/chordpro:latest make generate

      # Step 4: Upload the generated book.pdf as an artifact
      - name: Upload book.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: book.pdf